services:
  web:
    image: ghcr.io/roseratugo/roserat-ugo.com:latest
    container_name: roserat-ugo-portfolio
    networks:
      - proxy_net
    restart: unless-stopped
    ports:
      - "55345:80"

networks:
  proxy_net:
    external: true
